name = "Duckling"
description = "Feature-rich and modern theme"
license = "MIT"
homepage = "https://git.aparoksha.dev/david-swift/duckling"
min_version = "0.19.0"
demo = "https://duckling.aparoksha.dev"

[author]
name = "david-swift"
homepage = "https://david.aparoksha.dev"
